stages:
 - configure
 - build
 - test

artifacts:
paths:
- build/

configure:
 stage: configure
 script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug

build:
 stage: build
 script:
  - cd build
  - make

test:
 stage: test
 script:
  - cd build
  - make test