branches:
  only:
    - master
before_install:
  - sudo apt-get install -qq check
  - sudo pip install cpp-coveralls
language: c
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug
script:
  - make
after_script:
  - make test
  - cd ../
  - if [ ${CC} = "gcc" ]; then coveralls --build-root "./build" --repo_token ${COVERALLS_TOKEN} --exclude python --exclude stub --exclude doc --exclude unittests; fi
